### PR TITLE
Fix Dwarf ID handling and enhance build process

### PR DESCRIPTION
**Pull request by styelz**
Correct inconsistencies in Dwarf ID handling between Bluetooth and IP connections. Improve the GitHub Actions workflow for building executables and managing artifacts. Add power down functionality to the GUI and update documentation accordingly. Clean up configuration and build scripts for better maintainability.

@stevejcl 
I noticed when the Bluetooth connection fails it sets the DWARF_IP and DWARF_ID in the config to None and I need to go back to the settings tab to apply the values saved there.

DWARF_IP = "None"
DWARF_ID = "None"

Also, when I try using bluetooth with the setupBLE executable i get errors. I have not been able to connect via BLE so far.

```
root_level: 10
Error moving log file: [WinError 32] The process cannot access the file because it is being used by another process: 'astro_session.log'
file_log_level: 10
Log file updated to: astro_session.log
##############
Config Values:
Wifi PSD: DWARF3_1
Wifi STAT SSID: WiFi-9RH4U
Wifi STAT PWD: *******
##############
Final Values:
Wifi PSD: DWARF3_1
Wifi STAT SSID: WiFi-9RH4U
Wifi STAT PWD: *******
##############
Start of Function connect_ble_dwarf_win
Exception in callback BleakScannerWinRT._received_handler(<winrt._winrt...00272F0842210>, <winrt._winrt...00272F0842250>)
handle: <Handle BleakScannerWinRT._received_handler(<winrt._winrt...00272F0842210>, <winrt._winrt...00272F0842250>)>
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.12.10\x64\Lib\asyncio\events.py", line 88, in _run
  File "C:\hostedtoolcache\windows\Python\3.12.10\x64\Lib\site-packages\bleak\backends\winrt\scanner.py", line 156, in _received_handler
AttributeError: module 'winrt.windows.foundation.collections' has no attribute '_IVector'
Exception in callback BleakScannerWinRT._received_handler(<winrt._winrt...00272F0842150>, <winrt._winrt...00272F0842170>)
```

### CODE REVIEW

**Comment by stevejcl** [comment]
yes, the IP and Id are reset during Bluetooth connection, it sets when ok.
The problem with Bluetooth could be due to python version, 3.12 I had the same problem with asyncio and Bluetooth lib. the Bluetooth  exe conection standalone is build with 3.11, didn t work with 3.12

**Comment by stevejcl** [comment]
just a question, how do you connect to your devices without using Bluetooth ?  I'm curious about that ?. I have also a function to get the id after been connected : it s a web call directly to the dwarf. need to verify the name...

you found it, it's update_get_config_data but, the id returns is the correct one no need to subtrack one on the id: see the result of my Dwarf3 you can check on yours at the end : http://{IP}:8082/getDefaultParamsConfig 
image

**Comment by stevejcl** [comment]
> yes, the IP and Id are reset during Bluetooth connection, it sets when ok. The problem with Bluetooth could be due to python version, 3.12 I had the same problem with asyncio and Bluetooth lib. the Bluetooth exe conection standalone is build with 3.11, didn t work with 3.12

that why in the workflow I build the bluetooth exe (setupBle.py) with python 3.11

     - name: Set up Python3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-local.txt --target .
          pip install cx_Freeze

      - name: Build the executable with setupBle.py
        run: |
          python setupBle.py build

      - name: Mode and rename to extern
        run: |
          powershell Move-Item -Path build\exe.win-amd64-3.11 -Destination build\exe.win-amd64-3.12\extern

      - name: create symbolic link
        run: |
           cmd /c mklink .\build\exe.win-amd64-3.12\extern\config.py .\build\exe.win-amd64-3.12\config.py
           cmd /c mklink .\build\exe.win-amd64-3.12\extern\config.ini .\build\exe.win-amd64-3.12\config.ini

**Comment by JohnDickinson-cnic** [comment]
Hi @stevejcl , 

> just a question, how do you connect to your devices without using Bluetooth ? I'm curious about that ?. I have also a function to get the id after been connected : it s a web call directly to the dwarf. need to verify the name...
> 

I have my dwarf setup to connect to my lan wifi. I have a static dhcp entry set for the dwarf so it always has IP 192.168.1.42. I just connect to the IP directly. No bluetooth.

> you found it, it's update_get_config_data but, the id returns is the correct one no need to subtrack one on the id: see the result of my Dwarf3 you can check on yours at the end : http://{IP}:8082/getDefaultParamsConfig image

OK, I will recheck that.

**Comment by styelz** [comment]
Hi @stevejcl 

> just a question, how do you connect to your devices without using Bluetooth ? I'm curious about that ?. I have also a function to get the id after been connected : it s a web call directly to the dwarf. need to verify the name...
> 

I connect direct to the DwarfIP which has a static IP assigned using DHCP so it always has the same IP. Then I just click No on bluetooth and click Start Scheduler and it connects with no bluetooth required.

image

My Device settings are set to STA mode, so it connects to the LAN wifi automatically.

image

If connect via IP and it fails, the config.py is reset , same as BLE did. I think I will need to re apply the settings after the connection is closed

> you found it, it's update_get_config_data but, the id returns is the correct one no need to subtrack one on the id: see the result of my Dwarf3 you can check on yours at the end : http://{IP}:8082/getDefaultParamsConfig image

I will take a better look at this.

Also, I tried python 3.11 and still the same error.

```
Exception in callback BleakScannerWinRT._received_handler(<BluetoothLEA...00167CF439050>, <BluetoothLEA...00167CF439FD0>)
handle: <Handle BleakScannerWinRT._received_handler(<BluetoothLEA...00167CF439050>, <BluetoothLEA...00167CF439FD0>)>
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\asyncio\events.py", line 84, in _run
  File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\bleak\backends\winrt\scanner.py", line 156, in _received_handler
AttributeError: module 'winrt.windows.foundation.collections' has no attribute '_IVector'
```

**Comment by stevejcl** [comment]
=> My Device settings are set to STA mode, so it connects to the LAN wifi automatically.

After startup ? for me it never connects to my Wifi Network automatically, need bluetooth first.

For bleak I have these versions installed : 

(myenv3) PS L:\AstroPhoto\Tools\JCL\astro_dwarf_session-main\astro_dwarf_session> python -m pip list
Package                                                 Version
------------------------------------------------------- --------
babel                                                   2.17.0
bcrypt                                                  4.3.0
bleak                                                   1.1.0
certifi                                                 2025.8.3
cffi                                                    1.17.1
charset-normalizer                                      3.4.3
cryptography                                            45.0.6
filelock                                                3.19.1
flatbuffers                                             25.2.10
geographiclib                                           2.1
h3                                                      4.3.1
idna                                                    3.10
inputimeout                                             1.0.4
invoke                                                  2.2.0
numpy                                                   2.3.2
paramiko                                                4.0.0
pip                                                     24.0
protobuf                                                3.20.3
pycparser                                               2.22
PyNaCl                                                  1.5.0
requests                                                2.32.5
timezonefinder                                          8.0.0
tk                                                      0.1.0
tkcalendar                                              1.6.1
typing_extensions                                       4.15.0
urllib3                                                 2.5.0
websockets                                              11.0.3
winrt-runtime                                           3.2.1
winrt-Windows.Devices.Bluetooth                         3.2.1
winrt-Windows.Devices.Bluetooth.Advertisement           3.2.1
winrt-Windows.Devices.Bluetooth.GenericAttributeProfile 3.2.1
winrt-Windows.Devices.Enumeration                       3.2.1
winrt-Windows.Foundation                                3.2.1
winrt-Windows.Foundation.Collections                    3.2.1
winrt-Windows.Storage.Streams                           3.2.1

you are using windows, right ?

**Comment by stevejcl** [comment]
you can also use Web Browser for bluetooth with checking the correcponding checkox, it will not use bleak but a web page

**Comment by styelz** [comment]
Yea I am on windows. Still not working. Maybe it is the bluetooth adapter on my laptop. I also tried web browser but when it connects it fails with incorrect password error even though it is the correct password. I am running the latest firmware on the dwarf3.  Maybe you can try downloading one of my builds [here](https://github.com/styelz/astro_dwarf_session/releases/tag/v1.7.1) and see if it works on your hardware.

Here is my pip list for python 3.11 BLE build env. It is the same versions as yours except for cryptography 
```
(myenv3) PS C:\Users\pbp16\Desktop\Dwarf-schedule-tool\astro_dwarf_session> python -V
Python 3.11.6

(myenv3) PS C:\Users\pbp16\Desktop\Dwarf-schedule-tool\astro_dwarf_session> pip list
Package                                                 Version
------------------------------------------------------- --------
babel                                                   2.17.0
bcrypt                                                  4.3.0
bleak                                                   1.1.0
cabarchive                                              0.2.4
certifi                                                 2025.8.3
cffi                                                    1.17.1
charset-normalizer                                      3.4.3
cryptography                                            45.0.7
cx_Freeze                                               8.4.0
cx_Logging                                              3.2.1
filelock                                                3.19.1
flatbuffers                                             25.2.10
geographiclib                                           2.1
geopy                                                   2.4.1
h3                                                      4.3.1
idna                                                    3.10
inputimeout                                             1.0.4
invoke                                                  2.2.0
lief                                                    0.16.6
numpy                                                   2.3.2
packaging                                               25.0
paramiko                                                4.0.0
pillow                                                  11.3.0
pip                                                     23.2.1
protobuf                                                3.20.3
pycparser                                               2.22
PyNaCl                                                  1.5.0
pyserial                                                3.5
pytz                                                    2025.2
requests                                                2.32.5
setuptools                                              80.9.0
striprtf                                                0.0.29
timezonefinder                                          8.0.0
tk                                                      0.1.0
tkcalendar                                              1.6.1
typing_extensions                                       4.15.0
urllib3                                                 2.5.0
websockets                                              11.0.3
winrt-runtime                                           3.2.1
winrt-Windows.Devices.Bluetooth                         3.2.1
winrt-Windows.Devices.Bluetooth.Advertisement           3.2.1
winrt-Windows.Devices.Bluetooth.GenericAttributeProfile 3.2.1
winrt-Windows.Devices.Enumeration                       3.2.1
winrt-Windows.Foundation                                3.2.1
winrt-Windows.Foundation.Collections                    3.2.1
winrt-Windows.Storage.Streams                           3.2.1
```

**Comment by styelz** [comment]
For IP only without bluetooth, you need to put the telescope in STA (client) mode as I showed in the screenshot above.
Once this is done you can connect to the dwarf direct via IP no bluetooth is needed.

**Comment by styelz** [comment]
OK I got it to work with BLE using the Web Browser.
